### ISSUE TITLE
Link to page in PDF

### ISSUE THREAD

**Issue by draperunner** [draperunner/readme-db#2]
Link directly to the specific article page in the pdf by appending `#page=XX` to the pdf link. For example: http://readme.abakus.no/utgaver/2014/2014-03.pdf#page=8

If one pdf page contains two magazine pages, as most of the pdfs do, one cannot simply append the magazine page number to the link. `Math.floor(magPage / 2) + 1`

**Comment by essoen** [comment]
> If one pdf page contains two magazine pages, as most of the pdfs do, one cannot simply append the magazine page number to the link. Math.floor(magPage / 2) + 1

You can just jump to the first of the pages?

**Comment by draperunner** [comment]
I think you misunderstand. See this link: http://readme.abakus.no/utgaver/2014/2014-03.pdf#page=8
It refers to page 8 (Gløsløken) but page 8 in the pdf is Flørt. The formula `Math.floor(magPage / 2) + 1` should work if the pdf layout is similar as for 2014-03

**Comment by essoen** [comment]
Ah, so that have to be used for those editions. I'll update my pull request. Does the correct format start with 2014-04?

**Comment by draperunner** [comment]
Looks like this is the pattern:

2013-06 or newer:
    pdfPage = Math.floor(magazinePage / 2) + 1
2013-05:
    pdfPage = magazinePage
Older:
    ISSUU link. Cannot link to specific page, so just ignore these.

**Comment by essoen** [comment]
Alright, I'll update my pull request
