### ISSUE TITLE
Bulk adding articles

### ISSUE THREAD

**Issue by essoen** [draperunner/readme-db#6]
This would be very useful when adding a whole edition: The possibility to set the edition, then through a table add the information for all the articles, then pressing add once to have all added.

It's not a necessary feature, but it would be very useful.

**Comment by draperunner** [comment]
Yep! And editing articles directly in the search result table, if logged in. But that's maybe a separate issue.

**Comment by draperunner** [comment]
Commit 847cf6d7da8c544c42bcf311a069cdd007105fb6 simplifies adding an edition. You still add one article at a time, but you only enter edition number once, and type (spalte) is automatically filled in, and page number incremented. The focus is automatically set to the page field when "add article" is clicked.

Experience will show if this is efficient or if improvements should be made.

**Comment by essoen** [comment]
It worked nicely when adding the edition `2016-01`, so I don't think we need any more bulk functionality. Maybe have som infobox about how it works?
